theme: jekyll-theme-minimal
title: Matt Gillie
description: Data Scientist & AI Safety
logo: /assets/profile.png # Optional: Upload a photo to an 'assets' folder later if you want
show_downloads: false
google_analytics: 
